import { 
  Injectable, HttpException, HttpStatus, NotFoundException, 
  BadRequestException, ConflictException, Inject, forwardRef
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { JwtService } from '@nestjs/jwt'; 
import * as bcrypt from 'bcrypt';
import { MailService } from './mail.service';

@Injectable()
export class AuthService {
  constructor(
    @Inject(forwardRef(() => PrismaService))
    private prisma: PrismaService,
    @Inject(forwardRef(() => JwtService))
    private jwtService: JwtService,
    @Inject(forwardRef(() => MailService))
    private mailService: MailService 
  ) {}

  async register(data: any) {
    const { fullName, email, password, unit } = data; // 🔥 username dihapus, unit diambil
    const cleanEmail = (email || '').trim().toLowerCase();

    const allowedDomains = ['@btn.co.id', '@bankbsn.co.id', '@bsn.co.id', '@gmail.com'];
    const isDomainValid = allowedDomains.some((domain) => cleanEmail.endsWith(domain));

    if (!isDomainValid) {
      throw new BadRequestException('Pendaftaran gagal. Harus menggunakan email resmi instansi.');
    }

    // Cek apakah email sudah ada
    let user = await this.prisma.user.findUnique({ where: { email: cleanEmail } });

    if (user) {
      if (user.isVerified) {
        throw new ConflictException('Email sudah terdaftar dan aktif!');
      }
      // Kalau belum aktif, kita timpa passwordnya dan kirim ulang token (biar gak nyangkut)
    }

    const hashedPassword = await bcrypt.hash(password, 10);

    // Generate EmployeeID kalau user baru
    if (!user) {
      const existingUsers = await this.prisma.user.findMany({
        where: { employeeId: { startsWith: 'BSN-USR-' } },
        select: { employeeId: true },
      });

      let maxNumber = 0;
      existingUsers.forEach((u) => {
        if (u.employeeId) {
          const num = parseInt(u.employeeId.split('-')[2], 10);
          if (!isNaN(num) && num > maxNumber) maxNumber = num;
        }
      });
      const autoGeneratedId = `BSN-USR-${String(maxNumber + 1).padStart(3, '0')}`;

      user = await this.prisma.user.create({
        data: {
          employeeId: autoGeneratedId,
          fullName: fullName,
          email: cleanEmail,
          password: hashedPassword,
          divisi: unit || 'KC Semarang', // Simpan data dropdown unit ke tabel divisi
          role: 'USER',
          isVerified: false, // 🔥 Akun dibuat tapi digembok
        },
      });
    } else {
      user = await this.prisma.user.update({
        where: { id: user.id },
        data: { password: hashedPassword, fullName: fullName, divisi: unit },
      });
    }

    // 🔥 Buat Token JWT 5 Menit untuk Verifikasi
    const verifyToken = this.jwtService.sign({ sub: user.id, email: user.email }, { 
      secret: process.env.JWT_SECRET || 'rahasia-reset', 
      expiresIn: '5m' 
    });

    // Kirim Email
    await this.mailService.sendVerificationEmail(user.email, verifyToken, user.fullName || 'User');

    return { message: 'Registrasi berhasil, silakan periksa email Anda.', employeeId: user.employeeId };
  }

  async verifyEmail(token: string) {
    try {
      const decoded = this.jwtService.verify(token, { secret: process.env.JWT_SECRET || 'rahasia-reset' });
      
      await this.prisma.user.update({
        where: { email: decoded.email },
        data: { isVerified: true, hasSignedUp: true }
      });
      return { success: true, message: 'Email berhasil diverifikasi!' };
    } catch (error) {
      throw new BadRequestException('Token verifikasi tidak valid atau sudah kedaluwarsa (lewat 5 menit).');
    }
  }

  // --- LOGIN HANYA MENGGUNAKAN EMAIL ---
  async login(email: string, pass: string) {
    const cleanEmail = (email || '').trim().toLowerCase();

    const user = await this.prisma.user.findUnique({
      where: { email: cleanEmail }
    });

    if (!user) throw new HttpException('Email tidak terdaftar', HttpStatus.UNAUTHORIZED);
    
    // 🔥 CEK VERIFIKASI SEBELUM MASUK
    if (!user.isVerified) {
      throw new HttpException('Email belum diverifikasi. Cek kotak masuk Anda!', HttpStatus.FORBIDDEN);
    }
    
    if (user.is_suspended) throw new HttpException('Akses Ditolak! Akun Anda ditangguhkan.', HttpStatus.FORBIDDEN);
    if (user.deleted_at) throw new HttpException('Akses Ditolak! Akun ini telah dihapus.', HttpStatus.FORBIDDEN);
    if (!user.password) throw new HttpException('Password tidak valid.', HttpStatus.UNAUTHORIZED);

    const isMatch = await bcrypt.compare(pass, user.password);
    if (!isMatch) throw new HttpException('Password salah', HttpStatus.UNAUTHORIZED);

    const userRole = user.role || 'USER';
    const payload = { sub: user.id, email: user.email, role: userRole };
    
    return {
      access_token: await this.jwtService.signAsync(payload),
      role: userRole, 
      user: {
        id: user.id, email: user.email, employeeId: user.employeeId,
        role: userRole, namaLengkap: user.fullName, 
      }
    };
  }

  // Fungsi forgotPassword, resetPassword, getProfile, updateProfile biarkan sama persis seperti kode sebelumnya.
  async forgotPassword(email: string) {
    const cleanEmail = (email || '').trim().toLowerCase();
    const allowedDomains = ["@btn.co.id", "@bankbsn.co.id", "@bsn.co.id", "@gmail.com"];
    if (!allowedDomains.some(domain => cleanEmail.endsWith(domain))) {
      throw new BadRequestException('Akses ditolak. Gunakan email resmi instansi.');
    }

    const user = await this.prisma.user.findFirst({ where: { email: cleanEmail } });
    if (!user) throw new NotFoundException('Alamat email tidak terdaftar di sistem.');

    const resetToken = this.jwtService.sign({ sub: user.id, email: user.email }, { 
      secret: process.env.JWT_SECRET || 'rahasia-reset', expiresIn: '15m' 
    });

    await this.mailService.sendResetPasswordEmail(user.email, resetToken, user.fullName || 'User');
    return { message: 'Link reset password berhasil dikirim ke email.' };
  }

  async resetPassword(email: string, newPass: string, token: string) {
    if (!token) throw new BadRequestException('Token reset password tidak ditemukan.');
    const cleanEmail = (email || '').trim().toLowerCase();

    try {
      const decoded = this.jwtService.verify(token, { secret: process.env.JWT_SECRET || 'rahasia-reset' });
      if (decoded.email !== cleanEmail) throw new BadRequestException('Token tidak cocok.');

      const hashedPassword = await bcrypt.hash(newPass, 10);
      await this.prisma.user.update({
        where: { id: decoded.sub }, data: { password: hashedPassword },
      });
      return { message: 'Password berhasil diperbarui!' };
    } catch (error) {
      throw new BadRequestException('Link reset password tidak valid atau sudah kadaluarsa.');
    }
  }

  async getProfile(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true, employeeId: true, email: true, fullName: true,
        divisi: true, phone: true, avatar: true, role: true, is_suspended: true, deleted_at: true, 
      },
    });
    if (!user) throw new NotFoundException('User tidak ditemukan');
    if (user.is_suspended) throw new HttpException('Akun ditangguhkan.', HttpStatus.FORBIDDEN);
    return user;
  }

  async updateProfile(userId: string, data: any) {
    return this.prisma.user.update({
      where: { id: userId },
      data: {
        fullName: data.fullName, employeeId: data.employeeId, email: data.email,
        divisi: data.divisi, phone: data.phone, avatar: data.avatar,
      },
      select: { id: true, fullName: true, email: true, divisi: true, phone: true, avatar: true, role: true }
    });
  }
}