import { 
  Injectable, 
  HttpException, 
  HttpStatus, 
  NotFoundException, 
  BadRequestException, 
  ConflictException,
  Inject,
  forwardRef
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { JwtService } from '@nestjs/jwt'; 
import * as bcrypt from 'bcrypt';
import { MailService } from './mail.service';

@Injectable()
export class AuthService {
  constructor(
    @Inject(forwardRef(() => PrismaService))
    private prisma: PrismaService,

    // 🔥 TAMBAHKAN INJECT & FORWARDREF UNTUK JWTSERVICE DI SINI 🔥
    @Inject(forwardRef(() => JwtService))
    private jwtService: JwtService,
    
    @Inject(forwardRef(() => MailService))
    private mailService: MailService 
  ) {}

  async register(data: any) {
    const { fullName, username, email, password } = data;

    const cleanEmail = (email || '').trim().toLowerCase();
    const cleanUsername = (username || '').trim().toLowerCase();

    const allowedDomains = ['@btn.co.id', '@bankbsn.co.id', '@bsn.co.id'];
    const isDomainValid = allowedDomains.some((domain) =>
      cleanEmail.endsWith(domain),
    );

    if (!isDomainValid) {
      throw new BadRequestException(
        'Pendaftaran gagal. Harus menggunakan email resmi BSN (@btn.co.id, @bankbsn.co.id, @bsn.co.id)',
      );
    }

    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [
          { email: { equals: cleanEmail, mode: 'insensitive' } },
          { username: { equals: cleanUsername, mode: 'insensitive' } }
        ],
      },
    });

    if (existingUser) {
      throw new ConflictException('Email atau Username sudah terdaftar di sistem!');
    }

    const existingUsers = await this.prisma.user.findMany({
      where: { employeeId: { startsWith: 'BSN-USR-' } },
      select: { employeeId: true },
    });

    let maxNumber = 0;
    existingUsers.forEach((u) => {
      if (u.employeeId) {
        const parts = u.employeeId.split('-');
        const num = parseInt(parts[parts.length - 1], 10);
        if (!isNaN(num) && num > maxNumber) {
          maxNumber = num;
        }
      }
    });

    const nextNumber = String(maxNumber + 1).padStart(3, '0');
    const autoGeneratedId = `BSN-USR-${nextNumber}`;

    const hashedPassword = await bcrypt.hash(password, 10);

    const newUser = await this.prisma.user.create({
      data: {
        employeeId: autoGeneratedId,
        fullName: fullName || cleanUsername,
        username: cleanUsername,
        email: cleanEmail,
        password: hashedPassword,
        role: 'USER',
        hasSignedUp: true,
      },
    });

    return { 
      message: 'Registrasi berhasil', 
      user: newUser.username,
      employeeId: newUser.employeeId 
    };
  }

  // --- FUNGSI LOGIN ---
  async login(username: string, pass: string) {
    const cleanInput = (username || '').trim().toLowerCase();

    const user = await this.prisma.user.findFirst({
      where: {
        OR: [
          { username: { equals: cleanInput, mode: 'insensitive' } },
          { email: { equals: cleanInput, mode: 'insensitive' } }
        ]
      }
    });

    if (!user) throw new HttpException('User tidak ditemukan', HttpStatus.UNAUTHORIZED);
    if (user.is_suspended) throw new HttpException('Akses Ditolak! Akun Anda ditangguhkan.', HttpStatus.FORBIDDEN);
    if (user.deleted_at) throw new HttpException('Akses Ditolak! Akun ini telah dihapus.', HttpStatus.FORBIDDEN);
    if (!user.password) throw new HttpException('Password tidak valid. Registrasi ulang.', HttpStatus.UNAUTHORIZED);

    const isMatch = await bcrypt.compare(pass, user.password);
    if (!isMatch) throw new HttpException('Password salah', HttpStatus.UNAUTHORIZED);

    const userRole = user.role || 'USER';
    const payload = { sub: user.id, username: user.username, role: userRole };
    
    return {
      access_token: await this.jwtService.signAsync(payload),
      role: userRole, 
      user: {
        id: user.id,
        username: user.username,
        email: user.email,
        employeeId: user.employeeId,
        role: userRole,
        namaLengkap: user.fullName, 
      }
    };
  }

  // 🔥 FORGOT PASSWORD (KIRIM EMAIL + GENERATE TOKEN)
  async forgotPassword(email: string) {
    const cleanEmail = (email || '').trim().toLowerCase();

    // 1. Validasi Domain (Tambahkan @gmail.com untuk testing Nodemailer)
    const allowedDomains = ["@btn.co.id", "@bankbsn.co.id", "@bsn.co.id", "@gmail.com"];
    const isDomainValid = allowedDomains.some(domain => cleanEmail.endsWith(domain));

    if (!isDomainValid) {
      throw new BadRequestException('Akses ditolak. Gunakan email resmi instansi.');
    }

    // 2. Cek apakah user ada di DB
    const user = await this.prisma.user.findFirst({ 
      where: { email: { equals: cleanEmail, mode: 'insensitive' } } 
    });
    
    if (!user) {
      throw new NotFoundException('Alamat email tidak terdaftar di sistem.');
    }

    // 3. Buat Token JWT Sementara (Berlaku 15 menit)
    const payload = { sub: user.id, email: user.email };
    const resetToken = this.jwtService.sign(payload, { 
      secret: process.env.JWT_SECRET || 'rahasia-reset', 
      expiresIn: '15m' 
    });

    // 4. Kirim Email Asli via Nodemailer
    await this.mailService.sendResetPasswordEmail(user.email, resetToken, user.fullName || user.username);

    return { message: 'Link reset password berhasil dikirim ke email.' };
  }

  // 🔥 RESET PASSWORD (VERIFIKASI TOKEN & UPDATE DB)
  async resetPassword(email: string, newPass: string, token: string) {
    if (!token) throw new BadRequestException('Token reset password tidak ditemukan.');

    const cleanEmail = (email || '').trim().toLowerCase();

    try {
      // 1. Verifikasi masa berlaku dan keaslian token
      const decoded = this.jwtService.verify(token, { secret: process.env.JWT_SECRET || 'rahasia-reset' });

      if (decoded.email !== cleanEmail) {
        throw new BadRequestException('Token tidak cocok dengan email ini.');
      }

      // 2. Hash Password Baru
      const hashedPassword = await bcrypt.hash(newPass, 10);

      // 3. Simpan Password Baru ke DB
      await this.prisma.user.update({
        where: { id: decoded.sub },
        data: { password: hashedPassword },
      });

      return { message: 'Password berhasil diperbarui!' };
    } catch (error) {
      throw new BadRequestException('Link reset password tidak valid atau sudah kadaluarsa. Silakan request ulang.');
    }
  }

  // 🔥 AMBIL PROFIL & UPDATE PROFIL
  async getProfile(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true, employeeId: true, username: true, email: true, fullName: true,
        divisi: true, phone: true, avatar: true, role: true, is_suspended: true, deleted_at: true, 
      },
    });

    if (!user) throw new NotFoundException('User tidak ditemukan');
    if (user.is_suspended) throw new HttpException('Akun ditangguhkan.', HttpStatus.FORBIDDEN);
    if (user.deleted_at) throw new HttpException('Akun dinonaktifkan.', HttpStatus.FORBIDDEN);

    return user;
  }

  async updateProfile(userId: string, data: any) {
    return this.prisma.user.update({
      where: { id: userId },
      data: {
        fullName: data.fullName, employeeId: data.employeeId, email: data.email,
        divisi: data.divisi, phone: data.phone, avatar: data.avatar,
      },
      select: {
        id: true, fullName: true, email: true, divisi: true, phone: true, avatar: true, role: true,
      }
    });
  }
}